include "base-config.conf"

kafka {
  input.topic = "sunbirddev.learning.graph.events"
  output.audit.topic = "sunbirddev.telemetry.raw"
  output.obsrv.topic = "output.topic"
  groupId = "sunbirddev-transaction-event-processor-group"
  error.topic = "sunbirddev.learning.events.failed"
}

task {
  consumer.parallelism = 1
  parallelism = 1
  producer.parallelism = 1
  window.time = 60
  router.parallelism = 1
  compositeSearch.parallelism = 1
  dialcodeIndexer.parallelism = 1
  dialcodemetricsIndexer.parallelism = 1
}

schema {
  basePath = "https://sunbirddev.blob.core.windows.net/sunbird-content-dev/schemas/local"
}

channel.default = "org.sunbird"

job {
  audit-event-generator = false
  audit-history-indexer = false
  obsrv-metadata-generator = true
  composite-search-indexer = true
  dialcode-indexer = false
  dialcode-metrics-indexer = false
  env = "sunbirddev"
}

compositesearch.index.name = "compositesearch"
nested.fields = ["badgeAssertions", "targets", "badgeAssociations", "me_totalTimeSpent", "me_totalPlaySessionCount", "me_totalTimeSpentInSec", "provider", "osMetadata", "actions"]
string.only.fields = ["interceptionPoints", "editorState", "variants", "timeLimits", "contentTypesCount", "mimeTypesCount", "lhs_options", "rhs_options", "options", "answer", "reservedDialcodes", "issuer", "signatoryList", "data"]
schema.definition_cache.expiry = 14400
restrict {
  metadata.objectTypes = []
  objectTypes = ["EventSet", "Questionnaire", "Misconception", "FrameworkType", "EventSet", "Event"]
}

janusgraph {
  storage {
    host = "localhost"
    port = "9042"
    backend = "cql"
    keyspace = "janusgraph"
    cql {
      read-consistency-level = "LOCAL_QUORUM"
      write-consistency-level = "ONE"
      local-datacenter = "datacenter1"
    }
  }
  log {
    learning_graph_events {
      backend = "default"
    }
  }
}

cloudstorage.metadata.replace_absolute_path=false
cloudstorage.relative_path_prefix= "CONTENT_STORAGE_BASE_PATH"
cloudstorage.read_base_path="https://sunbirddev.blob.core.windows.net"
cloudstorage.mecloudstorage.metadata.list=["appIcon","posterImage","artifactUrl","downloadUrl","variants","previewUrl","pdfUrl", "streamingUrl", "toc_url"]
cloud_storage_container="sunbird-content-dev"
