package org.sunbird.job.dialcodecontextupdater.util

object DialcodeContextUpdaterConstants {

  val COMMA_SEPARATOR = ", "
  val X_CHANNEL_ID = "X-Channel-Id"
  val UPDATE = "UPDATE"
  val CREATE = "CREATE"
  val CONTENT_TYPE = "contentType"
  val IDENTIFIER = "identifier"
  val DESCRIPTION = "description"
  val LIMIT = "limit"
  val NAME = "name"
  val VISIBILITY = "visibility"
  val CHANNEL = "channel"
  val CONTENT = "content"
  val STATUS = "status"
  val ORIGIN = "origin"
  val OBJECT_TYPE = "objectType"
  val ORIGIN_DATA = "originData"
  val VERSION_KEY = "versionKey"
  val RESULT = "result"
  val CONTENT_TYPE_HEADER = "Content-Type"
  val BEARER = "Bearer "
  val MESSAGES = "messages"
  val APPLICATION_JSON = "application/json"
  val REQUEST = "request"
  val SEARCH = "search"
  val FILTERS = "filters"
  val SEARCH_MODE = "mode"
  val FIELDS = "fields"
  val X_AUTHENTICATED_USER_TOKEN = "x-authenticated-user-token"
  val CATEGORIES = "categories"
  val TTL = "ttl"
  val DIALCODES = "dialcodes"
}
