package org.sunbird.job.contentautocreator.util

object ContentAutoCreatorConstants {

  val COMMA_SEPARATOR = ", "
  val X_CHANNEL_ID = "X-Channel-Id"
  val UPDATE = "UPDATE"
  val CREATE = "CREATE"
  val CONTENT_TYPE = "contentType"
  val IDENTIFIER = "identifier"
  val DESCRIPTION = "description"
  val LIMIT = "limit"
  val NAME = "name"
  val LINKED_CONTENT = "linkedContent"
  val CHANNEL = "channel"
  val CONTENT = "content"
  val STATUS = "status"
  val ORIGIN = "origin"
  val OBJECT_TYPE = "objectType"
  val ORIGIN_DATA = "originData"
  val VERSION_KEY = "versionKey"
  val REPOSITORY = "repository"
  val INDEX = "index"
  val RESULT = "result"
  val CONTENT_TYPE_HEADER = "Content-Type"
  val BEARER = "Bearer "
  val MESSAGES = "messages"
  val APPLICATION_JSON = "application/json"
  val REQUEST = "request"
  val SEARCH = "search"
  val FILTERS = "filters"
  val EXISTS = "exists"
  val FIELDS = "fields"
  val MIME_TYPE = "mimeType"
  val APP_ICON = "appIcon"
  val X_AUTHENTICATED_USER_TOKEN = "x-authenticated-user-token"
  val CATEGORIES = "categories"
  val CODE = "code"
  val TERMS = "terms"
  val TTL = "ttl"
  val FINAL_STATUS = List("Live", "Unlisted", "Processing")
}
