package org.sunbird.job.publish.helpers

object MimeType extends Enumeration {

  val PDF = Value("application/pdf")
  val EPUB = Value("application/epub")
  val MSWORD = Value("application/msword")
  val H5P_Archive = Value("application/vnd.ekstep.h5p-archive")

  val X_Youtube = Value("video/x-youtube")
  val Youtube = Value("video/youtube")
  val X_URL_FILE = Value("text/x-url")

  val ECML_Archive = Value("application/vnd.ekstep.ecml-archive")
  val HTML_Archive =Value("application/vnd.ekstep.html-archive")
  val Android_Package =Value("application/vnd.android.package-archive")
  val Content_Archive =Value("application/vnd.ekstep.content-archive")

  val ASSETS = Value("assets")
  val Plugin_Archive = Value("application/vnd.ekstep.plugin-archive")
  val Collection =Value("application/vnd.ekstep.content-collection")

  val Content_Package =Value("application/octet-stream")
  val JSON_FILE =Value("application/json")
  val JS_FILE =Value("application/javascript")
  val XML_FILE =Value("application/xml")
  val TEXT_FILE =Value("text/plain")
  val HTML_FILE =Value("text/html")
  val TEXT_JS_FILE =Value("text/javascript")
  val TEXT_XML_FILE =Value("text/xml")
  val CSS_FILE =Value("text/css")
  val JPEG_Image =Value("image/jpeg")
  val JPG_Image =Value("image/jpg")
  val PNG_Image =Value("image/png")
  val TIFF_Image =Value("image/tiff")
  val BMP_Image =Value("image/bmp")
  val GIF_Image =Value("image/gif")
  val SVG_XML_Image =Value("image/svg+xml")
  val QUICK_TIME_Image =Value("image/x-quicktime")
  val AVI_Video =Value("video/avi")
  val AVI_MS_VIDEO_Video =Value("video/msvideo")
  val AVI_X_MS_VIDEO_Video =Value("video/x-msvideo")
  val QUICK_TIME_Video =Value("video/quicktime")
  val X_QUICK_TIME_Video =Value("video/x-qtc")
  val III_gpp_Video =Value("video/3gpp")
  val MP4_Video =Value("video/mp4")
  val OGG_Video =Value("video/ogg")
  val WEBM_Video =Value("video/webm")
  val MP3_MPEG_Audio =Value("video/mpeg")
  val MP3_X_MPED_Audio =Value("video/x-mpeg")
  val MP3_Audio =Value("audio/mp3")
  val MP3_MPEG3_Audio =Value("audio/mpeg3")
  val MP3_X_MPEG3_Audio =Value("audio/x-mpeg-3")
  val MP4_Audio =Value("audio/mp4")
  val MPEG_Audio =Value("audio/mpeg")
  val OGG_Audio =Value("audio/ogg")
  val OGG_VORBIS_Audio =Value("audio/vorbis")
  val WEBM_Audio =Value("audio/webm")
  val X_WAV_Audio =Value("audio/x-wav")
  val X_FONT_TTF =Value("application/x-font-ttf")
}
