package org.sunbird.job.publish.helpers

object MimeType extends Enumeration {

  val PDF: MimeType.Value = Value("application/pdf")
  val EPUB: MimeType.Value = Value("application/epub")
  val MSWORD: MimeType.Value = Value("application/msword")
  val H5P_Archive: MimeType.Value = Value("application/vnd.ekstep.h5p-archive")

  val X_Youtube: MimeType.Value = Value("video/x-youtube")
  val Youtube: MimeType.Value = Value("video/youtube")
  val X_URL_FILE: MimeType.Value = Value("text/x-url")

  val ECML_Archive: MimeType.Value = Value("application/vnd.ekstep.ecml-archive")
  val HTML_Archive: MimeType.Value = Value("application/vnd.ekstep.html-archive")
  val Android_Package: MimeType.Value = Value("application/vnd.android.package-archive")
  val Content_Archive: MimeType.Value = Value("application/vnd.ekstep.content-archive")

  val ASSETS: MimeType.Value = Value("assets")
  val Plugin_Archive: MimeType.Value = Value("application/vnd.ekstep.plugin-archive")
  val Collection: MimeType.Value = Value("application/vnd.ekstep.content-collection")

  val Content_Package: MimeType.Value = Value("application/octet-stream")
  val JSON_FILE: MimeType.Value = Value("application/json")
  val JS_FILE: MimeType.Value = Value("application/javascript")
  val XML_FILE: MimeType.Value = Value("application/xml")
  val TEXT_FILE: MimeType.Value = Value("text/plain")
  val HTML_FILE: MimeType.Value = Value("text/html")
  val TEXT_JS_FILE: MimeType.Value = Value("text/javascript")
  val TEXT_XML_FILE: MimeType.Value = Value("text/xml")
  val CSS_FILE: MimeType.Value = Value("text/css")
  val JPEG_Image: MimeType.Value = Value("image/jpeg")
  val JPG_Image: MimeType.Value = Value("image/jpg")
  val PNG_Image: MimeType.Value = Value("image/png")
  val TIFF_Image: MimeType.Value = Value("image/tiff")
  val BMP_Image: MimeType.Value = Value("image/bmp")
  val GIF_Image: MimeType.Value = Value("image/gif")
  val SVG_XML_Image: MimeType.Value = Value("image/svg+xml")
  val QUICK_TIME_Image: MimeType.Value = Value("image/x-quicktime")
  val AVI_Video: MimeType.Value = Value("video/avi")
  val AVI_MS_VIDEO_Video: MimeType.Value = Value("video/msvideo")
  val AVI_X_MS_VIDEO_Video: MimeType.Value = Value("video/x-msvideo")
  val QUICK_TIME_Video: MimeType.Value = Value("video/quicktime")
  val X_QUICK_TIME_Video: MimeType.Value = Value("video/x-qtc")
  val III_gpp_Video: MimeType.Value = Value("video/3gpp")
  val MP4_Video: MimeType.Value = Value("video/mp4")
  val OGG_Video: MimeType.Value = Value("video/ogg")
  val WEBM_Video: MimeType.Value = Value("video/webm")
  val MP3_MPEG_Audio: MimeType.Value = Value("video/mpeg")
  val MP3_X_MPED_Audio: MimeType.Value = Value("video/x-mpeg")
  val MP3_Audio: MimeType.Value = Value("audio/mp3")
  val MP3_MPEG3_Audio: MimeType.Value = Value("audio/mpeg3")
  val MP3_X_MPEG3_Audio: MimeType.Value = Value("audio/x-mpeg-3")
  val MP4_Audio: MimeType.Value = Value("audio/mp4")
  val MPEG_Audio: MimeType.Value = Value("audio/mpeg")
  val OGG_Audio: MimeType.Value = Value("audio/ogg")
  val OGG_VORBIS_Audio: MimeType.Value = Value("audio/vorbis")
  val WEBM_Audio: MimeType.Value = Value("audio/webm")
  val X_WAV_Audio: MimeType.Value = Value("audio/x-wav")
  val X_FONT_TTF: MimeType.Value = Value("application/x-font-ttf")
}
